on:
  push:
    branches:
      - master
  page_build:
  release:
    types:
      - created

jobs:
  build_and_test:
    name: Column Seprator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release --all-features
